source 'https://github.com/CocoaPods/Specs.git'

def import_pods
	pod "RUTextSize", :path => "../"
end

target 'RUTextSize', :exclusive => true do
	import_pods
end

target 'Tests', :exclusive => true do
	import_pods

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
